services:
  - type: web
    name: project-idea-lab
    env: node
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: API_KEY
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: NOTION_CLIENT_ID
        sync: false
      - key: NOTION_CLIENT_SECRET
        sync: false
      - key: FIGMA_CLIENT_ID
        sync: false
      - key: FIGMA_CLIENT_SECRET
        sync: false