/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
export default {
  'Artistic & Photographic': {
    description: "Embrace creativity with styles inspired by traditional art, photography, and pop culture. This collection is your gateway to transforming portraits into expressive masterpieces, from classical paintings to modern graphic designs.",
    Playful: {
      description: "Inject a dose of fun into your photos with these lighthearted and whimsical transformations.",
      banana: { description: "Go bananas! This effect places the subject in a silly, bright yellow banana costume." },
      beard: { description: "Give your subject a magnificent, larger-than-life beard for a touch of lumberjack chic or wizardly wisdom." },
      lego: { description: "Reimagine the subject as a classic LEGO minifigure, complete with plastic sheen and iconic blocky form." }
    },
    'Pop Culture Characters': {
      description: "Become an icon from the worlds of animation, film, and art. This category lets you step into the shoes of your favorite characters.",
      adventureTime: { description: "Journey to the Land of Ooo by transforming into a character with the whimsical, noodle-limbed style of Adventure Time." },
      pixar: { description: "Leap into a world of heartfelt animation by reimagining the subject as a 3D character with the signature charm and detail of a Pixar film." },
      disney: { description: "Become royalty with the classic, enchanting animation style of a Disney Prince or Princess, set against a fairy-tale backdrop." },
      ghibli: { description: "Capture the gentle, painterly, and nostalgic atmosphere of a Studio Ghibli masterpiece." },
      dragonBall: { description: "Power up! Transform into a Dragon Ball Z warrior with dynamic lines, intense energy, and iconic spiky hair." },
      sailorMoon: { description: "In the name of the moon, adopt the iconic 90s shōjo anime style of Sailor Moon, complete with large, sparkling eyes." },
      harryPotter: { description: "Enter the Wizarding World as a student of Hogwarts, complete with robes and a wand." },
      wonderWoman: { description: "Channel your inner Amazonian princess with the iconic tiara and heroic pose of Wonder Woman." },
      sherlock: { description: "Don a deerstalker hat and solve a mystery in the foggy streets of Victorian London as Sherlock Holmes." },
      fridaKahlo: { description: "Embody the surreal and powerful style of Frida Kahlo, featuring her iconic unibrow and bold, symbolic imagery." },
      elvis: { description: "Become the King of Rock and Roll, capturing the stage presence and iconic style of Elvis Presley." }
    },
    Eras: {
      description: "Travel through time and adopt the aesthetics of different historical periods, from classical art to vintage photography.",
      renaissance: { description: "Render your portrait with the dramatic lighting, rich tones, and classical composition of a Renaissance masterpiece." },
      '19century': { description: "Capture the formal, haunting quality of a 19th-century daguerreotype, with period-appropriate clothing and a sepia tint." },
      '80s': { description: "Go back to the decade of big hair and bold colors with a classic 1980s yearbook photo aesthetic." },
      old: { description: "Age the subject gracefully, adding wrinkles, wisdom, and the gentle softness of advanced years." },
      baroquegold: { description: "Embrace the drama and opulence of the Baroque period with dramatic lighting, gilded details, and luxurious textures." },
      tintype: { description: "Recreate the authentic, slightly imperfect look of a wet-plate collodion tintype from the 19th century, known for its unique chemical artifacts." }
    },
    Mediums: {
      description: "Explore a diverse palette of artistic materials and techniques. This category transforms your photo as if it were created with physical media.",
      cartoon: { description: "Simplify your portrait into a clean, friendly cartoon with bold lines and solid colors." },
      anime: { description: "Adopt the expressive and stylized look of a modern anime character, featuring large eyes and detailed hair." },
      comic: { description: "Become a comic book hero, complete with halftone dots, dynamic ink lines, and a graphic sensibility." },
      impressionist: { description: "See the world through the eyes of an Impressionist painter, with soft, visible brushstrokes and a focus on light and color." },
      fauvism: { description: "Unleash bold, non-naturalistic colors and expressive brushwork in the style of the Fauvist art movement." },
      artnouveau: { description: "Embrace the elegant, organic, and decorative style of Art Nouveau, characterized by flowing lines and natural motifs." },
      cubism: { description: "Deconstruct your portrait into geometric forms and multiple viewpoints, in the revolutionary style of Cubism." },
      ukiyoe: { description: "Transform your photo into a traditional Japanese ukiyo-e woodblock print, with flat colors and delicate linework." },
      watercolor: { description: "Achieve the soft, translucent, and flowing effect of a watercolor painting, complete with paper grain." },
      oilimpasto: { description: "Apply thick, textured layers of oil paint with visible palette-knife strokes for a dynamic, tactile surface." },
      charcoal: { description: "Create a classic, expressive charcoal sketch with rich blacks, smudged tones, and a focus on form." },
      statue: { description: "Carve your portrait from classical marble, turning the subject into a timeless, elegant statue." },
      papercraft: { description: "Reconstruct the subject from layers of cut and folded paper, creating a charming, handcrafted 3D effect." },
      claymation: { description: "Mold your portrait from modeling clay, complete with the charming imperfections and soft look of stop-motion animation." },
      stainedglass: { description: "Render the image as a luminous stained glass window, with bold leaded lines and vibrant, transparent colors." },
      mosaic: { description: "Assemble your portrait from tiny, colored tiles (tesserae) to create a timeless mosaic effect." },
      filmnoir: { description: "Enter a world of mystery and shadow with high-contrast black-and-white lighting, sharp shadows, and a moody atmosphere." },
      noircolor: { description: "Combine the dramatic, low-key lighting of film noir with a muted, modern color palette for a stylish, cinematic look." },
      cinematic: { description: "Apply a professional, movie-like color grade with popular palettes like teal-and-orange for a polished, cinematic feel." },
      polaroid: { description: "Capture the nostalgic, slightly faded look of a vintage instant Polaroid photo, complete with its iconic white frame." },
      surrealcollage: { description: "Create a dreamlike and unexpected image by collaging disparate elements in a surrealist style." },
      graffiti: { description: "Become a piece of urban art by stenciling the portrait onto a textured brick wall with spray paint and street art elements." },
      halftoneprint: { description: "Simulate a vintage printing process using visible CMYK dots to build up the image, creating a retro, graphic look." },
      sciillustration: { description: "Transform the portrait into a precise and detailed scientific illustration, as if from an antique textbook." }
    },
    'Poster & Graphic': {
      description: "Apply principles of graphic design to your portrait, turning it into a bold, stylized piece of poster art.",
      psychedelic: { description: "Embrace the vibrant, swirling, and mind-bending aesthetic of 1960s psychedelic poster art." },
      bauhaus: { description: "Reconstruct your portrait using the minimalist principles of the Bauhaus school: geometric shapes, primary colors, and clean composition." },
      swiss: { description: "Adopt the clean, grid-based, and highly functional aesthetic of the Swiss International Style of graphic design." },
      brutalist: { description: "Create a stark, raw, and unapologetically bold image with the heavy forms and textured surfaces of Brutalist design." },
      botanical: { description: "Frame your portrait with elegant, detailed botanical engravings for a calm and natural feel." },
      blueprint: { description: "Redraw your portrait as a technical blueprint, with white lines on a cyan background and precise annotations." }
    },
    'Master Photographers': {
      description: "Emulate the signature styles of some of history's most iconic photographers, from dramatic landscapes to intimate portraits.",
      anselAdams: { description: "Capture the epic, sharp, and tonally rich look of Ansel Adams' black-and-white large-format landscape photography." },
      cartierBresson: { description: "Adopt the 'decisive moment' philosophy of Henri Cartier-Bresson with a candid, geometric, and natural-light 35mm black-and-white style." },
      dorotheaLange: { description: "Channel the humane, empathetic, and documentary spirit of Dorothea Lange's portraiture from the WPA era." },
      richardAvedon: { description: "Create a minimalist, high-key studio portrait against a stark white background, in the style of Richard Avedon." },
      irvingPenn: { description: "Achieve the elegant, sculpted, and immaculate stillness of an Irving Penn studio portrait." },
      dianeArbus: { description: "Capture the direct, intimate, and often unsettling honesty of a flash-lit, square-format Diane Arbus portrait." },
      helmutNewton: { description: "Embrace the glossy, hard-lit, and provocative style of Helmut Newton's black-and-white fashion photography." },
      annieLeibovitz: { description: "Create a rich, cinematic, and grandly narrative portrait with the sculpted lighting and storytelling of Annie Leibovitz." },
      sebastiaoSalgado: { description: "Render an epic, high-contrast, and deeply textured black-and-white documentary image in the style of Sebastião Salgado." },
      steveMcCurry: { description: "Capture the vivid, saturated colors and expressive, soulful eyes that define the reportage style of Steve McCurry." },
      robertCapa: { description: "Emulate the gritty, raw immediacy and motion-filled grain of Robert Capa's legendary war photography." },
      gordonParks: { description: "Adopt the lyrical, elegant, and socially conscious documentary style of Gordon Parks, in either black-and-white or muted color." },
      vivianMaier: { description: "Capture the quiet, candid, and reflective moments of street life in the unassuming square-format style of Vivian Maier." },
      williamEggleston: { description: "Find beauty in the banal with the rich, dye-transfer color and subtle geometry of William Eggleston's vernacular photography." },
      saulLeiter: { description: "Create a muted, painterly, and layered color photograph using reflections and obstructions, in the style of Saul Leiter." },
      daidoMoriyama: { description: "Embrace the high-contrast, grainy, and restless energy of Daidō Moriyama's raw black-and-white street photography." },
      peterLindbergh: { description: "Achieve the honest, natural, and timeless monochrome fashion portraiture style of Peter Lindbergh." },
      maryEllenMark: { description: "Capture the intimate, candid, and empathetic realism of Mary Ellen Mark's black-and-white documentary portraits." },
      brassai: { description: "Evoke the romantic, nocturnal atmosphere of Brassaï's Paris, with wet streets, mist, and dramatic streetlights." },
      walkerEvans: { description: "Adopt the formal, restrained, and detailed compositions of Walker Evans' seminal American documentary work." }
    }
  },
  'Technical & Media Emulation': {
    description: "Recreate the distinct aesthetics of analog and digital technologies. This collection is perfect for achieving a vintage, retro, or CG-specific feel by simulating the artifacts and characteristics of different media.",
    'Film & Process Emulations': {
      description: "Simulate the unique color, grain, and character of iconic photographic film stocks and classic darkroom techniques.",
      kodachrome64: { description: "Achieve the sharp, vibrant, and archival look of Kodachrome 64 slide film, famous for its rich reds and clean blues." },
      portra400: { description: "Emulate the soft, natural skin tones and gentle contrast of Kodak Portra 400, a favorite for portrait photography." },
      portra800: { description: "Capture the warm tones and slightly coarser grain of Kodak Portra 800, excellent for low-light situations." },
      ektachromeE100: { description: "Reproduce the clean, neutral, and cool-leaning colors of Ektachrome E100 slide film." },
      velvia50: { description: "Get the high-saturation, punchy contrast, and vivid colors of Fujifilm Velvia 50, a classic choice for landscape photography." },
      provia100f: { description: "Achieve the balanced, refined, and moderately saturated look of Fujifilm Provia 100F slide film." },
      fuji400h: { description: "Emulate the airy, pastel tones and signature mint-green cast of Fujifilm 400H, popular for wedding photography." },
      cinestill800t: { description: "Recreate the unique cinematic look of CineStill 800T, with its signature red halation around highlights in night scenes." },
      vision3_250d: { description: "Capture the muted saturation and wide dynamic range of Kodak Vision3 250D daylight-balanced cinema film." },
      vision3_500t: { description: "Emulate the soft contrast and teal-leaning shadows of Kodak Vision3 500T tungsten-balanced cinema film." },
      polaroid600: { description: "Achieve the soft, cool-toned, and slightly unpredictable look of classic Polaroid 600 instant film." },
      polaroidSX70: { description: "Reproduce the warm, delicate, and vintage tones of the iconic Polaroid SX-70 instant film." },
      fp100c: { description: "Emulate the rich, neutral colors and smooth grain of Fujifilm FP-100C, a classic peel-apart instant film." },
      ilfordHP5: { description: "Get the punchy, grainy, and versatile character of Ilford HP5, a classic black-and-white documentary film stock." },
      triX400: { description: "Achieve the gritty, high-contrast, and timeless reportage look of Kodak Tri-X 400 black-and-white film." },
      tmax3200: { description: "Emulate the heavy grain and dramatic contrast of Kodak T-Max 3200, designed for extremely low-light photography." },
      aerochromeIR: { description: "Create the surreal, false-color look of Kodak Aerochrome infrared film, which turns foliage into vibrant reds and pinks." },
      lomographyPurple: { description: "Achieve the psychedelic color-shifting effect of Lomography Purple film, turning greens into purples." },
      crossProcessC41inE6: { description: "Simulate the unpredictable, high-contrast, and color-shifted look of cross-processing film in the wrong chemicals." },
      bleachBypass: { description: "Recreate the desaturated, high-contrast, and metallic look of the bleach bypass film development process." }
    },
    'Analog Carriers & Signal Path Artifacts': {
      description: "Simulate the charming imperfections and nostalgic artifacts from analog media formats like VHS tapes, CRT screens, and old broadcast signals.",
      crtPhosphor: { description: "Recreate the look of an image displayed on a vintage CRT monitor, complete with scanlines and phosphor dot triads." },
      vhsEpTape: { description: "Emulate the low-fidelity charm of a VHS tape in long-play mode, with chroma bleed, tape noise, and tracking errors." },
      betacamSp: { description: "Achieve the clean, professional look of a Betacam SP broadcast tape, the standard for news gathering in the 90s." },
      minidvInterlace: { description: "Reproduce the distinct interlaced look of early MiniDV camcorders, with characteristic motion artifacts." },
      laserdiscComposite: { description: "Simulate the analog video artifacts of a LaserDisc player, such as dot crawl and rainbowing on fine patterns." },
      ntscGhosting: { description: "Recreate the look of a weak over-the-air NTSC television signal, complete with multipath ghosting and antenna snow." },
      timebaseWobble: { description: "Emulate the horizontal jitter and shimmer of analog tape playback without time-base correction." },
      macrovisionTear: { description: "Simulate the chaotic visual failure of Macrovision VHS copy protection, with unstable brightness and tearing." },
      analogPhotocopyGen5: { description: "Achieve the high-contrast, grainy, and slightly distorted look of a fifth-generation analog photocopy." },
      faxThermalRoll: { description: "Recreate the dithered, streaky, and low-resolution aesthetic of an image sent through a thermal fax machine." },
      risographDuotone: { description: "Emulate the look of a two-color Risograph print, with its characteristic misregistration, coarse halftone, and soy-ink texture." },
      cyanotypeBlueprint: { description: "Achieve the deep Prussian blue and soft, contact-printed look of a classic Cyanotype photographic print." },
      photogramContact: { description: "Create a camera-less photogram image, with object silhouettes and diffuse glows, as if made in a darkroom." },
      pinholeLongExposure: { description: "Simulate the soft focus, wide vignette, and motion blur of a long exposure taken with a simple pinhole camera." },
      slitScanPortrait: { description: "Create a surreal, time-stretched portrait using the slit-scan photography technique, smearing features along one axis." },
      lenticularPrint: { description: "Emulate the ribbed, parallax-shifting effect of a lenticular print, which shows different images from different angles." },
      hologramDiffraction: { description: "Achieve the rainbow diffraction fringes and metallic sheen of an embossed security hologram." },
      ccdBloomSmear: { description: "Reproduce the vertical smear and blooming artifacts from bright highlights characteristic of older CCD digital sensors." },
      rollingShutterJello: { description: "Simulate the 'jello' effect of a rolling shutter on a CMOS sensor, which skews vertical lines during fast motion." },
      screenMoiréCapture: { description: "Recreate the wavy interference patterns (moiré) that occur when photographing a digital screen." }
    },
    'CGI & Digital': {
      description: "Explore aesthetics born from the world of computer graphics, from early pixel art to futuristic digital styles.",
      '8bit': { description: "Transform your portrait into nostalgic 8-bit pixel art, with a limited color palette and low resolution." },
      lowpoly: { description: "Reconstruct the subject as a low-poly 3D model with flat-shaded, geometric facets." },
      blueprint3d: { description: "Convert your portrait into a clean, technical 3D wireframe, revealing its underlying geometric structure." },
      vaporwave: { description: "Embrace the nostalgic, retro-futuristic aesthetic of Vaporwave, with neon gradients and 80s digital artifacts." },
      synthwave: { description: "Create a dramatic, neon-lit portrait with the cinematic 80s synth-pop aesthetic of Synthwave." },
      cyberpunk: { description: "Enter a high-tech, low-life future with a Cyberpunk portrait featuring neon lights, rain, and cybernetic enhancements." },
      glitch: { description: "Introduce digital errors and artifacts like scan lines, datamoshing, and RGB splits for a chaotic, corrupted look." },
      neonoutline: { description: "Trace the contours of the subject with glowing neon lines against a dark background for a striking, high-contrast effect." },
      holofoil: { description: "Make your portrait appear as if it's printed on iridescent holographic foil with shifting rainbow colors." },
      xray: { description: "Create an artistic x-ray effect, revealing the bone structure beneath the skin in a stylized, translucent way." },
      infrared: { description: "Simulate a thermal infrared camera view, mapping the subject's temperature to a vibrant color gradient." },
      chrome: { description: "Transform the subject into a sleek, reflective liquid chrome sculpture with mirror-like surfaces." }
    },
    '3D Render Qualities & Pipelines': {
      description: "Apply the specific techniques and looks from the world of modern 3D computer graphics, from realistic rendering to stylized shaders.",
      pbrFilmic: { description: "Achieve a photorealistic look with physically-based rendering (PBR), image-based lighting, and a cinematic Filmic tonemap." },
      clayAoTurntable: { description: "Render the subject as a neutral monochrome clay model with strong ambient occlusion to emphasize form." },
      toonRampNPR: { description: "Create a non-photorealistic (NPR) cel-shaded look with stepped color ramps and crisp ink outlines." },
      matcapStudio: { description: "Apply a 'material capture' (MatCap) shader to simulate complex studio lighting and reflections with a single texture." },
      sssSkin: { description: "Simulate realistic skin by adding subsurface scattering (SSS), which mimics light penetrating and diffusing through translucent surfaces." },
      thinFilmIridescence: { description: "Create a beautiful, iridescent, soap-bubble-like effect with a thin-film interference shader." },
      carPaintFlakes: { description: "Recreate the multi-layered look of metallic car paint, complete with base coat, metallic flakes, and a glossy clear coat." },
      brushedMetalAniso: { description: "Simulate the elongated highlights and soft reflections of brushed metal using an anisotropic shader." },
      microDisplacement: { description: "Add incredible surface detail by using micro-displacement to alter the actual geometry of the model at render time." },
      parallaxOcclusion: { description: "Create the illusion of 3D surface detail and self-shadowing on a flat plane using parallax occlusion mapping." },
      triplanarNoise: { description: "Apply a seamless procedural texture, like rock or noise, using triplanar projection to avoid UV mapping artifacts." },
      raymarchSDF: { description: "Render the subject using Signed Distance Fields (SDFs), creating crisp, mathematically perfect shapes and soft ambient occlusion." },
      pathTraceGI: { description: "Achieve ultimate realism with path-traced global illumination, simulating how light bounces and bleeds color in a scene." },
      voxelAO: { description: "Create a stylized, blocky look with voxel-based ambient occlusion and global illumination." },
      volumetricGodRays: { description: "Add dramatic, atmospheric 'God rays' (crepuscular rays) by rendering light shafts through participating media like fog or dust." },
      causticsPhoton: { description: "Simulate the bright, focused patterns of light (caustics) that occur when light passes through or reflects off refractive materials like glass and water." },
      bokehDoF: { description: "Achieve a cinematic, shallow depth-of-field effect with beautifully shaped bokeh, mimicking a real camera lens." },
      wireframeHiddenLine: { description: "Create a technical, hidden-line wireframe view, where only the visible edges of the model are drawn." },
      uvCheckerInspect: { description: "Apply a UV checker map to the subject to visualize the quality and layout of its texture coordinates." },
      curvatureCavity: { description: "Emphasize surface detail by using a curvature map to darken crevices (cavities) and lighten sharp edges, simulating wear and tear." },
      pointCloudSurfels: { description: "Render the subject as a dense cloud of points or 'surfels' (surface elements) for a scanned, reconstructed look." },
      photogrammetryScan: { description: "Simulate the look of a high-poly 3D scan created with photogrammetry, including baked-in lighting and minor texture seams." },
      iridescentHolographicFoil: { description: "Apply a procedural holographic foil material with view-dependent rainbow diffraction and a metallic sheen." },
      stylizedClayToonMix: { description: "Combine the soft, matte look of clay with the crisp ramps and outlines of toon shading for a unique hybrid style." },
      gpuPathNoiseGrain: { description: "Retain a subtle, aesthetically pleasing amount of noise from an unbiased path-traced render to add cinematic texture." },
      acescgNeutral: { description: "Apply a neutral ACEScg color grade, a professional standard in filmmaking for preserving highlight detail and achieving a filmic look." }
    }
  },
  'Scientific & Abstract': {
    description: "Venture into the experimental with styles based on scientific visualization, mathematical concepts, and non-traditional imaging. This collection is for those who want to see the world in a different light, revealing hidden structures and abstract beauty.",
    'Exotic Optics & Non-Euclidean Capture': {
      description: "Explore what's possible beyond a normal lens. This category simulates scientific, abstract, and physically-based optical phenomena that bend the rules of perception.",
      plenopticArray: { description: "Simulate a light-field camera capture, which allows for effects like refocusing after the shot is taken." },
      codedAperture: { description: "Recreate the look of lensless imaging, where the image is computationally reconstructed from a patterned mask." },
      schlieren: { description: "Visualize invisible changes in air density, like heat or airflow, with the razor-sharp edges of Schlieren imaging." },
      shadowgraph: { description: "Capture high-speed density gradients as soft, detailed monochrome shadows, a technique used in fluid dynamics." },
      interferometry: { description: "Wrap the subject in the iridescent, contour-like fringe patterns created by light wave interference." },
      polarizationMicroscopy: { description: "Reveal the hidden crystalline structures and birefringent colors of a subject as seen through a cross-polarized microscope." },
      uvivf: { description: "Simulate UV-induced visible fluorescence, where parts of the subject glow in surreal colors under an ultraviolet light." },
      hyperspectralFalseColor: { description: "Map invisible light spectra (like infrared) to visible colors, revealing details the human eye can't see." },
      catadioptricMirror: { description: "Emulate the look of a mirror lens, characterized by its compressed perspective and distinctive donut-shaped bokeh." },
      anamorphicScope: { description: "Achieve the cinematic look of an anamorphic lens, with its signature oval bokeh and horizontal lens flares." },
      slitScanTime: { description: "Create a surreal, time-stretched portrait using the temporal slit-scan technique, smearing features along a time axis." },
      tofDepthFusion: { description: "Visualize the world as a time-of-flight depth camera does, with clean, stepped contours based on distance." },
      speckleCoherence: { description: "Apply the granular, shimmering pattern of laser speckle that occurs when a surface is illuminated by coherent light." },
      holographicOffAxis: { description: "Recreate the look of an off-axis hologram, complete with carrier fringes and a metallic, diffractive sheen." },
      stereographicPlanet: { description: "Project the entire scene into a 'tiny planet' aound the subject using a stereographic projection." },
      hyperbolicTiling: { description: "Warp the space around the subject into a Poincaré disk, a two-dimensional model of hyperbolic geometry." },
      fourDProjection: { description: "Imagine the subject as a 3D 'slice' of a 4D object, resulting in impossible overlaps and strange occlusions." },
      causticImaging: { description: "Form the image not with a lens, but with the focused, intricate patterns of light (caustics) passing through water or glass." },
      semLike: { description: "Achieve the monochrome, high-detail, and topological look of a Scanning Electron Microscope (SEM) image." },
      nerfBake: { description: "Simulate the unique look of a NeRF (Neural Radiance Field) reconstruction, with its characteristic floaters and view-dependent sparkle." }
    },
    'Computer-Vision Diagnostic Layers': {
      description: "Visualize the world as a machine sees it. This category applies overlays and transformations inspired by common computer vision algorithms.",
      gradCam: { description: "Overlay a semi-transparent Grad-CAM heatmap to visualize where a neural network 'looks' to make a decision, highlighting important features in warm colors." },
      integratedGradients: { description: "Apply an 'Integrated Gradients' attribution mask, showing which pixels were most influential in a model's prediction." },
      saliencyMap: { description: "Generate a saliency map, which highlights the most visually conspicuous or attention-grabbing parts of the image." },
      segmentationCityscapes: { description: "Apply a crisp semantic segmentation overlay, color-coding each pixel based on its class (e.g., person, sky, car) using the Cityscapes dataset palette." },
      instanceMasksCoco: { description: "Show each detected object instance with a distinct, translucent colored mask, as seen in datasets like COCO." },
      detectionBoxesYolo: { description: "Draw the bounding boxes, class labels, and confidence scores generated by an object detection model like YOLO." },
      keypointsOpenPose: { description: "Overlay a 2D skeletal structure of the person's pose, as detected by an algorithm like OpenPose." },
      faceLandmarksArkit: { description: "Render the dense mesh of facial landmarks used by augmented reality systems like ARKit to track facial expressions." },
      opticalFlowFarneback: { description: "Visualize motion in the scene with an optical flow field, which shows the direction and speed of pixel movement." },
      depthTurboColormap: { description: "Generate a monocular depth map and color-code it with the vibrant 'Turbo' colormap to show distance from the camera." },
      surfaceNormalsRGB: { description: "Visualize the 3D surface orientation of the subject by color-coding the per-pixel surface normals in RGB." },
      stereoDisparity: { description: "Simulate a stereo disparity map, which shows the difference in position of objects as seen from two cameras, indicating depth." },
      lidarPointCloud: { description: "Render the subject as a sparse point cloud, as if it were scanned by a LiDAR sensor." },
      uvUnwrapAtlas: { description: "Project a checkerboard UV atlas onto the subject to visualize its 3D model's texture coordinates." },
      retopoWireframe: { description: "Overlay a clean, quad-based wireframe that follows the natural topology of the face, used in 3D modeling." },
      normalsEdgeOcclusion: { description: "Combine stylized edge detection with ambient occlusion for a technical, x-ray-like sketch effect." },
      superresArtifacts: { description: "Visualize the difference (residual) between a low-resolution image and its AI-super-resolved version, highlighting what the AI added." },
      demosaicChecker: { description: "Simulate the 'demosaicing' process of a digital camera sensor, revealing common artifacts like zipper and maze patterns at edges." },
      jpegQuantViz: { description: "Expose the underlying 8x8 block grid and ringing artifacts of JPEG compression." },
      exifTelemetry: { description: "Add a minimalist, technical HUD (Heads-Up Display) showing the photo's EXIF metadata like shutter speed, ISO, and aperture." }
    },
    'Signal Domain Alchemy': {
      description: "Transform your image not by changing pixels directly, but by manipulating its underlying mathematical representations in the frequency and signal domains.",
      fftPhaseOnly: { description: "Reconstruct the image using only the phase information from its Fourier transform, resulting in ghostly, edge-focused images." },
      fftMagOnly: { description: "Reconstruct the image using only the magnitude (energy) from its Fourier transform, creating abstract textures that lack clear form." },
      phaseSwap: { description: "Create an uncanny hybrid by combining one image's magnitude spectrum with another's phase spectrum." },
      waveletBands: { description: "Decompose the image into multi-scale wavelet bands, allowing for independent manipulation of detail at different frequencies." },
      multiresPyramid: { description: "Blend a Laplacian pyramid of the image, boosting fine layers to sharpen detail while controlling halos." },
      bilateralCartoon: { description: "Apply a strong, edge-preserving bilateral filter to create flat, cartoon-like color regions with sharp outlines." },
      anisotropicDiffusion: { description: "Use anisotropic diffusion to smooth textures within regions while preserving or enhancing the edges between them." },
      seamCarveWarp: { description: "Subtly warp the image using seam carving, a content-aware resizing technique that intelligently removes or inserts low-importance pixel seams." },
      poissonRelight: { description: "Relight the subject by solving a Poisson equation in the gradient domain, preserving texture while shifting illumination." },
      retinexNormalize: { description: "Apply a multi-scale Retinex algorithm to even out illumination and expand shadow detail, mimicking human vision." },
      unsharpFilm80: { description: "Recreate the classic darkroom technique of unsharp masking for crisp micro-contrast and a tactile 'print' feel." },
      harrisCornersHUD: { description: "Overlay Harris corner interest points, used in computer vision to identify significant features in an image." },
      cannyInk: { description: "Extract the edges using the Canny edge detector and blend them as clean, vector-like ink lines over the original image." },
      voronoiCells: { description: "Quantize the image's tones into a Voronoi diagram, dividing the portrait into polygonal cells." },
      delaunayWire: { description: "Triangulate the image's features into a Delaunay mesh and render it as a fine wireframe overlay." },
      reactionDiffusionSkin: { description: "Lay a subtle, organic, Turing-like pattern over the subject using a Gray-Scott reaction-diffusion simulation." },
      sdfContourMap: { description: "Generate and display a topographic-like contour map of the face using Signed Distance Fields (SDFs)." },
      morphologyGranite: { description: "Apply a sequence of morphological operators (opening/closing) to create a granular, stone-like microtexture." },
      poissonDiskStipple: { description: "Render the portrait using Poisson-disk stippling, where dots are placed randomly but are guaranteed to be a minimum distance apart." },
      grayWorldConstancy: { description: "Apply an automatic white balance based on the 'gray-world' assumption, neutralizing any global color cast." }
    },
    'Procedural Manifest': {
      description: "Execute a set of highly detailed, multi-part instructions that define the subject, background, camera, lighting, and post-processing. These complex 'manifests' generate deeply artistic and specific outcomes.",
      hyperbolic_atrium: { description: "Project the subject and their environment into a mind-bending hyperbolic space, reminiscent of an M.C. Escher engraving." },
      meta_liquid_skin: { description: "Create a surreal portrait where the skin's material properties morph and shift based on its curvature, from diffuse to liquid metal." },
      chronos_slices: { description: "Extrude the subject through time, rendering them as a series of parallel slices, each made of a different material." },
      retopo_molt: { description: "Create the illusion of a 3D wireframe 'skin' peeling away from the face to reveal a realistic surface underneath." },
      caustic_projector: { description: "Form the image using only the focused light of caustics, as if projected through moving, distorted glass." },
      voxel_bokeh: { description: "Rasterize the subject into a cloud of translucent 3D pixels (voxels), where depth-of-field emerges from the density of the cloud itself." },
      drape_identity: { description: "Drape a simulated piece of ultra-thin cloth over the subject, inferring their features from the tension and folds of the fabric." },
      csg_chapel: { description: "Carve the portrait using Constructive Solid Geometry (CSG) booleans, creating architectural voids and spaces within the form." },
      lidar_dust_recon: { description: "Reconstruct the portrait from a swirling cloud of animated dust particles, as if captured by a LiDAR scan in a hazy room." },
      hologrid_parallax: { description: "Encode the subject within a semi-transparent 3D lattice, where their form is only revealed through parallax as the camera moves." },
      nonnewtonian_face: { description: "Make the subject's surface behave like a non-Newtonian fluid, hardening on impact and liquefying at rest." },
      nerf_multiview_ghost: { description: "Simulate the unique, ghostly artifacts of a Neural Radiance Field (NeRF) reconstruction, which only resolves into a clear image from a specific viewpoint." },
      mandel_dermis: { description: "Generate skin texture and pores using iterated fractal noise, creating an infinitely detailed and organic surface." },
      prism_identity: { description: "Split the subject into three misaligned RGB passes, as if viewed through a prism, to create a spectral, chromatic aberration effect." },
      papercraft_sections: { description: "Build the portrait from a series of stacked, laser-cut paper contours, like an architectural model." }
    }
  },
  'Conceptual & Narrative': {
    description: "Go beyond aesthetics and re-contextualize your portrait. These styles frame the image within a larger story, a set of rules, or a speculative scenario, turning a simple photo into a piece of narrative art.",
    'Mixed Styles for front and background': {
      description: "Create compelling composite images by combining one distinct artistic style for the subject with a completely different style for the background.",
      renaissance_x_blueprint: { description: "Juxtapose a classical Renaissance oil portrait with a technical, cyan-and-white blueprint background." },
      marbleStatue_x_neonNoir: { description: "Place a timeless, classical marble statue into the rain-soaked, neon-lit alley of a film noir." },
      anime_x_swissGrid: { description: "Combine the expressive, stylized look of an anime character with the clean, minimalist order of a Swiss International design grid." },
      claymation_x_cyanotype: { description: "Set a charming, hand-molded claymation character against the deep, monochromatic blues of a cyanotype print." },
      baroqueGold_x_microprint: { description: "Contrast an opulent, gilded Baroque portrait with the intricate, modern precision of security microprint." },
      toonRamp_x_guilloche: { description: "Merge the flat, bold look of cel-shading with the complex, interwoven linework of banknote guilloché patterns." },
      holoFoil_x_blackVoid: { description: "Make a shimmering, iridescent holographic foil subject pop against the infinite depth of a pure black void." },
      photogrammetry_x_risograph: { description: "Combine a high-fidelity, 3D-scanned photogrammetry model with the lo-fi, two-color charm of a Risograph print." },
      chromeLiquid_x_pastelStudio: { description: "Contrast a hyper-reflective, liquid chrome subject with the soft, gentle color gradients of a pastel studio backdrop." },
      sciIllustration_x_bokehNight: { description: "Place a precise, engraved scientific illustration of the subject against the soft, blurry bokeh of city lights at night." },
      wireframe_x_paperCollage: { description: "Set a clean, technical 3D wireframe model against a background of torn, layered, and tactile paper collage." },
      lowPoly_x_gradientField: { description: "Juxtapose a faceted, low-poly 3D subject with a smooth, modern, multi-stop gradient background." },
      sepiaTintype_x_dataTape: { description: "Blend a vintage, wet-plate tintype portrait with the retro-tech aesthetic of data-tape UI elements." },
      sssSkin_x_archViz: { description: "Place a subject with hyperrealistic, subsurface-scattered skin into the clean, minimalist environment of an architectural visualization." },
      legoMinifig_x_blueHour: { description: "Set a glossy, plastic LEGO minifigure against the dramatic, deep blues and light streaks of a blue-hour cityscape." },
      charcoalSketch_x_causticGlass: { description: "Subject: Charcoal portrait with smudged shading and bold contours. Background: Refracted light caustics dancing on a wall as if through rippled glass. Blend: Let caustics spill a little onto shoulders; keep face matte." },
      nprInk_x_hyperrealLab: { description: "Place a stylized, non-photorealistic ink drawing into the hyperrealistic, glossy setting of a modern laboratory." },
      hologramHUD_x_concreteWall: { description: "Project a semi-transparent, futuristic hologram of the subject against the raw, textured surface of a concrete wall." },
      ceramicGlaze_x_forestFog: { description: "Set a portrait with the crazed, glossy finish of glazed ceramic into a moody, atmospheric, and foggy forest." },
      bronzeBust_x_digitalGrid: { description: "Contrast a heavy, patinated bronze bust with a receding, glowing digital wireframe grid." }
    },
    'Documents & Security': {
      description: "Reframe your portrait as an official document or artifact, complete with the textures, stamps, and security features of bureaucratic life.",
      FOIA_redact: { description: "Apply heavy, rectangular black redaction bars, as if the image were part of a declassified government document." },
      watermark_notary: { description: "Embed a semi-transparent, embossed 'NOTARIZED' watermark, giving the image an official, certified look." },
      microprint_border: { description: "Surround the portrait with a security frame made of microprint that appears as a solid line from a distance." },
      guilloche_plate: { description: "Lay intricate, interwoven guilloché patterns behind the subject, mimicking the design of currency and certificates." },
      stamp_ink_office: { description: "Add the slightly uneven, ghosting look of overlapping rubber date stamps in classic office ink colors." },
      hologram_id: { description: "Overlay a rectangular, iridescent hologram patch, like those found on ID cards and passports." },
      ocr_tesseract: { description: "Simulate a flatbed scan ready for Optical Character Recognition (OCR), complete with crop marks and text boxes." },
      barcode_pdf417: { description: "Place a dense PDF417 barcode panel next to the portrait, as if it were part of a shipping label or ID." },
      qr_overlay: { description: "Include a crisp QR code in the corner, as if linking to additional verification or information." },
      tamper_evident: { description: "Add a partially peeled, tamper-evident security seal that leaves behind a 'VOID' pattern." },
      watermark_latent: { description: "Embed a subtle, near-invisible latent watermark that is only visible at certain angles, like on high-security documents." },
      cheque_courtesy: { description: "Introduce the microprint lines, dotted boxes, and anti-photocopy screened backgrounds found on a bank cheque." },
      red_ribbon_seal: { description: "Affix a satin red ribbon and an embossed paper seal, as if on a formal diploma or legal document." },
      blue_ink_signature: { description: "Add a realistic, wet-ink blue ballpoint signature with natural pressure variations." },
      docket_header: { description: "Place a formal court docket header at the top, giving the image the context of a legal proceeding." },
      postal_cancellation: { description: "Overlay the wavy lines and circular date stamp of a postal cancellation mark." },
      perforation_edge: { description: "Give the image a perforated edge, as if it were a ticket stub or a stamp." },
      ledger_grid: { description: "Add a pale green or blue accounting ledger grid behind the subject, as if on a page from a logbook." },
      uv_security_fluor: { description: "Sprinkle the image with fluorescent security fibers that would glow under an ultraviolet light." },
      watermark_diagonal_confidential: { description: "Apply a large, low-opacity 'CONFIDENTIAL' watermark diagonally across the image, like a classified document." }
    },
    'Cognitive / memory Forensics': {
      description: "Explore the strange and fascinating artifacts of perception and memory. This category simulates psychological phenomena, turning your portrait into a study of the mind's eye.",
      eideticAfterimage: { description: "Overlay a faint, complementary-color ghost image, mimicking the afterimage that persists after staring at something bright." },
      saccadeTrails: { description: "Draw faint motion streaks between the eyes, mouth, and hands, visualizing the rapid, jerky movements (saccades) of the eye." },
      troxlerFade: { description: "Simulate Troxler's fading, an optical illusion where the periphery of your vision fades away when you fixate on a central point." },
      binocularRivalry: { description: "Create a flickering, patchwork effect that mimics binocular rivalry, where the brain struggles to merge two different images." },
      motionInducedBlindness: { description: "Make small features of the face intermittently 'disappear' when the background is in motion, simulating motion-induced blindness." },
      scotomaMask: { description: "Place a soft, blind-spot-like mask (a scotoma) over part of the image, which is then plausibly 'filled in' by the brain." },
      aphantasiaLowImagery: { description: "Reduce the portrait to a simple line drawing with minimal detail, simulating the 'mind's eye' of someone with aphantasia." },
      pareidoliaClouds: { description: "Make the facial features subtly emerge from an abstract texture, like seeing faces in clouds (pareidolia)." },
      confabulationFill: { description: "Invent plausible but incorrect details where information is missing, mimicking the way the brain confabulates to fill memory gaps." },
      flashbulbMemory: { description: "Recreate the vivid, high-contrast, and emotionally charged look of a 'flashbulb memory' of a significant event." },
      repressionRedactions: { description: "Blur and desaturate emotionally charged regions of the face, as if the memory is being actively repressed." },
      dreamSeam: { description: "Stitch the portrait together from mismatched patches with inconsistent lighting, like the disjointed logic of a dream." },
      memoryPalaceCards: { description: "Annotate the portrait with index cards and keywords, as if it were part of a 'memory palace' mnemonic technique." },
      tipOfTongue: { description: "Mask a crucial feature with question marks, visualizing the frustrating 'tip-of-the-tongue' phenomenon." },
      dejaVuTiling: { description: "Create an eerie sense of familiarity (déjà vu) by repeating small, subtle patches of the image." },
      migraineAura: { description: "Superimpose the shimmering, zigzag patterns of a visual migraine aura over part of the image." },
      changeBlindnessDiptych: { description: "Create two almost-identical versions of the portrait and toggle between them, illustrating the difficulty of spotting small changes (change blindness)." },
      emotionalSalienceMap: { description: "Apply a heatmap that highlights the most emotionally salient regions of the face, like the eyes and mouth." },
      reminiscenceBump: { description: "Blend the portrait with an era-specific film stock from the subject's 'reminiscence bump' (ages 10-30), a period we remember most vividly." },
      forgettingCurve: { description: "Fade the image's detail exponentially from the center outward, visualizing the Ebbinghaus forgetting curve." }
    },
    'Narrative Artifacts': {
      description: "Frame your portrait as a fictional or historical object with a story to tell. Each style turns the image into a piece of evidence, a cultural relic, or a mysterious document.",
      mythCartographer: { description: "Interpret the portrait as a lost map from a mythical land, with routes etched on the skin and symbols at scars." },
      embassyOfDreams: { description: "Render the image as a visa to the dream world, complete with entry stamps and a hologram of last night's weather." },
      ghostOfProvenance: { description: "Treat the photo like a museum artifact with a long history, layering it with auction stickers and curator notes." },
      oralHistoryWeave: { description: "Overlay translucent quotes from imaginary witnesses, as if weaving an oral history around the subject." },
      bureaucraticHaunting: { description: "Make the portrait look like a document processed by an extinct, mysterious government ministry." },
      speculativeAutopsy: { description: "Annotate the face like a forensic diagram for an emotion that never existed." },
      climateMuseumLabel: { description: "Display the portrait as an exhibit from a future museum, with a label describing the 'climate-changed' era it came from." },
      folkRemedyPoster: { description: "Turn the image into a village notice for a folk remedy, with hand-drawn diagrams and tear-off blessings." },
      archiveLeak: { description: "Simulate a misfiled dossier from a leaked archive, with contradictory timestamps and cryptic Post-it notes." },
      ritualCalibration: { description: "Treat the portrait as a mystical device that requires ritual alignment, complete with tick marks and candle icons." },
      lichenReader: { description: "Let patterns grow over the image like urban lichens—reading time, stress, and weather. Keep face visible; growth forms act as subtitles of lived conditions." },
      borderlandBallad: { description: "Frame the portrait with handwritten song verses in two dialects that translate each other poorly. Leave deliberate disagreements in meaning; underline where translation fails." },
      planetOfArchives: { description: "Imagine the background as stacks of geological strata made of documents. Each layer carries a tiny card summarizing what the face “meant” that century." },
      tenderPropaganda: { description: "Design a soft, caring propaganda poster about being human. Pastel gradients, small promises in the margins, and a seal of a fictive ministry of gentleness." },
      counterfeitMemory: { description: "Issue the image as a “memory credit card.” Add EMV-like contacts, microtext of childhood smells, and a spending limit measured in forgiven mistakes." },
      fieldNotesFromTomorrow: { description: "Overlay a scientist’s notebook from five years ahead describing the subject in cautious, kind language. Include sketched thumbnails of alternate futures in the margin." },
      saintOfSmallActs: { description: "Canonize the person as a minor saint of mundane kindness. Add tiny ex-votos (bus tickets, safety pins), a gold leaf halo made from transit maps, and a calendar feast day." },
      rumorAtlas: { description: "Map rumors as isobands around the face. Warm colors = tender rumors; cool colors = sharp rumors. Place a tiny scale bar labeled “gossip per meter.”" },
      edibleIcon: { description: "Render the portrait as if printed on edible paper for a neighborhood bakery holiday. Include a recipe on the back, visible as a ghost through the sheet." },
      futureArcheologyKit: { description: "Package the image like a specimen in a future archaeology kit, with instructions on how to excavate the subject’s habits without breaking them." }
    },
    'Constraint-Bent Portrait Protocols': {
      description: "Apply a set of rules or 'laws' that the image renderer must obey. The final look emerges not from a style, but from the fascinating consequences of these constraints.",
      causalityFold: { description: "Animate the portrait so shading and shadows update from T+1 back toward T, leaving faint temporal “unupdates.” Hair motion reverses before the head moves; reflections show the next frame." },
      observerBias: { description: "Increase resolution and material fidelity only in peripheral vision; the center of gaze remains slightly under-detailed. As the viewer looks away, features sharpen where they are not looking." },
      conservationOfSilhouette: { description: "No operation may change the outer silhouette. Lighting, micro-displacement, and materials may morph wildly, but the external contour is preserved; the background absorbs any “forbidden” expansion as inward dents." },
      topologyBudget: { description: "Face must render with a hard cap on total edges. When detail exceeds the budget, edges are auctioned away: pores fuse, nostrils decimate, cheekbones pixelate into flat facets; wireframe labels show which edges were “sold.”" },
      entropyDrip: { description: "Image entropy must increase over time unless “remember” events occur. Without interaction, textures smear, UVs stretch, and normals dephase. On clicks or beats, crispness is restored in concentric rings." },
      wavefunctionFace: { description: "Materials are probabilistic per-pixel (skin 60%, ceramic 30%, chrome 10%). The map collapses to a single material only when the viewer hovers or looks directly; elsewhere it remains a dithered superposition." },
      counterfactualReflections: { description: "All reflective and refractive contributions are rendered from a plausible alternate timeline: the reflection smiles when the subject is neutral, blinks when eyes are open, etc. Direct lighting stays truthful." },
      negotiatedLighting: { description: "Background and subject “negotiate” photon budget each frame. If the background brightens by 1 EV, the subject dims proportionally, maintaining a constant global exposure; a tiny HUD shows the bargaining result." },
      borrowedAlbedo: { description: "Subject’s albedo must be sampled from the background only (no native color). Skin tones become reprojected patches of wall, floor, signage; geometry stays accurate but color is diegetic collage." },
      vetoedSpecular: { description: "Specular highlights only render on beats not divisible by 3 (or on frames where frameIndex % 6 ∈ {1,2}). On vetoed frames, specular is clamped to diffuse; produces strobing “truth windows” in gloss." },
      scafFold: { description: "Wireframe annotates itself with micro-lemmas: each edge prints the rule justifying its existence (crease, curvature, silhouette, seam). Edges without proof fade out until topology re-justifies them." },
      depthTax: { description: "Every centimeter behind the focal plane costs “depth credits.” When the budget is exceeded, far geometry collapses to billboards; near geometry gains tessellation and SSS. The tax HUD shows current spend." },
      antiAliasOath: { description: "Edges cannot exhibit shimmer. To obey, the renderer snaps subpixel motion to a rational grid; micro-jitter is redirected to the background as grain. Motion looks smoothly quantized, like oath-bound AA." },
      puncturedNormals: { description: "Normal vectors are forbidden in a masked region (e.g., a ring across the cheeks). In that band the surface renders only from curvature and AO; specular disappears and forms look embossed, almost paper-cut." },
      auctionedShadows: { description: "Every shadow ray must be purchased. The most “valuable” shadows (under nostrils, eye sockets) win the auction; low-value soft shadows fail to render and are replaced by pale placeholders with price tags." },
      parallaxDebate: { description: "Background and subject disagree about camera parallax by a small epsilon. As the camera moves, the subject’s depth cues lead slightly; the background lags, causing intentional micro-parallax dissonance." },
      memoryLeakSSS: { description: "Subsurface scattering radius increases monotonically in regions the viewer stares at, as if “heat” accumulates. Look away and the radius cools back slowly, leaving ghostly warmth trails in ears and nose." },
      centroidHandoff: { description: "Each frame, a random facial region becomes the “centroid owner.” Only that region may move the head’s root transform; everything else must compensate locally. Produces peculiar, believable micro-adjustments." },
      silentCollision: { description: "Collisions do not resolve with impulses; instead, interpenetrations are silently “painted over” by borrowing nearby albedo and normals, as if reality covers its mistakes. Works eerily well until the camera rakes across." }
    },
    'What If...': {
      description: "Ask speculative, thought-provoking questions and let the image answer. This category reframes the portrait in fascinating new contexts, turning it into a piece of conceptual art.",
      whatIf_authenticityOutlawed: { description: "What if authenticity is illegal? Render the portrait only via certified proxies: watermark chains, notarized overlays, and compliance margins. Any uncited region must blur or redact itself. Show a provenance sidebar that contradicts one entry." },
      whatIf_faceAsPublicUtility: { description: "What if the face is public infrastructure? Overlay it with transit-like schematics (service lines for gaze, speech, breath). Mark outages and maintenance windows. Background signage uses neutral civic typography; no branding." },
      whatIf_memoryRequiresQuorum: { description: "What if memory needs a quorum? Details appear only if three independent “witness annotations” agree. Disagreements render as grayscale placeholders with tally marks and confidence intervals." },
      whatIf_colorBudget: { description: "What if color has a budget? Assign a strict chroma quota to the image. Spend saturation on the most semantically loaded regions; elsewhere, tones desaturate to near-neutral. Display a small color-ledger with remaining credit." },
      whatIf_backgroundOwnsNarrative: { description: "What if the background owns the story? Keep the subject materially plain (matte clay). Shift all metadata, captions, and temporal events into the background: wall notes, taped receipts, light stains indicating prior scenes." },
      whatIf_translationIsLossy: { description: "What if translation must lose information? Render bilingual captions where each language drops a different 12% of meaning. Missing content becomes faint geometric placeholders anchored to the face regions it would have described." },
      whatIf_lawAsRecipe: { description: "What if law compiles to recipes? Express compliance as kitchen operations mapped to facial areas (sift, fold, proof). Add a structured footer: statute → operation → outcome, with one deliberate mismatch." },
      whatIf_privacyIsSpatial: { description: "What if privacy is a physical distance? Encode a “privacy radius” as depth: regions within R render sharp; outside, features self-abstract to coarse primitives. Draw the radius as a thin measure ring with tick marks." },
      whatIf_ecologyCoauthors: { description: "What if ecology co-authors the image? Let non-human agents introduce legible edits: lichen edge maps on hairlines, fungal gradients in shadow, insect bite perforations that reveal a second, older print beneath." },
      whatIf_receiptsForFeeling: { description: "What if feelings issue receipts? Attach a thermal receipt listing events the image charges you for (attention, care, avoidance) with line-item totals. The receipt must cast a shadow; totals never exactly reconcile with the portrait." },
      whatIf_reflectionIsSovereign: { description: "What if reflections refuse compliance? Mirrors and glossy surfaces render their own timeline. Keep direct light truthful; render specular channels from a slightly divergent pose and expression. Annotate delta as a small vector field." },
      whatIf_timeAsAxis: { description: "What if time runs left→right? Age gradients map horizontally across the face. Background signage shows datelines increasing to the right. Shadows shear accordingly; do not use crossfades." },
      whatIf_rumorErodesMatter: { description: "What if rumor erodes matter? Weather the surface proportionally to “circulation.” Highly discussed regions pit and flake; unspoken areas remain sharp. Include a small scale: mm lost per thousand mentions." },
      whatIf_archiveResistsReading: { description: "What if archives resist being read? Paper fibers dodge OCR: lines twist slightly when scanned; redactions leak gentler paraphrases in the margins. Keep one visible staple shadow with missing staple." },
      whatIf_identityLeased: { description: "What if identity is leased, not owned? Stamp lease terms onto the portrait frame (duration, scope, penalties). Expired features gray out with “revert to default” texture; active regions keep color." },
      whatIf_gravityIsAttention: { description: "What if gravity follows attention? Areas receiving viewer focus physically sag and crease; ignored regions float and simplify. Provide a minimal attention HUD with current “pull” values." }
    }
  }
}
